#Script can change password of N users each password is generated by genermdp.sh
#2 Parameters : 1st user name 2nd number of users

#If there is no parameter or more than two
if [ $# -eq 2 ] 
then
    x=$2
else
    echo"Syntax error : attribpwd prefix_username limit"
    return 1
fi

for i in $(seq 2 $x)
do
    . ./genermdp.sh $x
    echo $mdp | passwd --stdin $1$i
    echo "Changement de mot de passe de $1$i"
done


